name = "Alasdair Walker"
description = "The Financial Planning Geek"
keywords = "Alasdair Walker, financial planning, finance, personal finance, uk"
image = "jake.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://financialplanninggeek.github.io/"

[[sections]]
title = "Links"
description = "Find me online"
direction = "column"
item_style = "outline"
[[sections.items]]
# embed_url = "https://www.youtube.com/embed/x0gUY9ddjQY"
[[sections.items]]
title = "Optimum Path Financial Planning"
description = "My financial planning business"
url = "https://optimumpath.co.uk"
[[sections.items]]
title = "AI Lab"
description = "A collaboration with Nextwealth - AI best practice community for financial advice."
url = "https://nextwealth.co.uk/events/ai-lab/"



[[sections]]
title = "Social links"
description = "Gind me here"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/linkedin/ffffff"
title = "LinkedIn"
url = "www.linkedin.com/in/financialplanninggeek"
# [[sections.items]]
# icon = "https://cdn.simpleicons.org/imdb/ffffff"
# title = "IMDb"
# url = "https://www.imdb.com/name/nm0350453/"
# [[sections.items]]
# icon = "https://cdn.simpleicons.org/wikipedia/ffffff"
# title = "Wikipedia"
# url = "https://en.wikipedia.org/wiki/Jake_Gyllenhaal"
# [[sections.items]]
# title = "Rotten Tomatoes"
# icon = "https://cdn.simpleicons.org/rottentomatoes/ffffff"
# url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
